apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: eks-nginx
  name: eks-nginx
spec:
  replicas: 3
  selector:
    matchLabels:
      app: eks-nginx
  template:
    metadata:
      labels:
        app: eks-nginx
    spec:
      containers:
      - image: 387721658341.dkr.ecr.ap-northeast-2.amazonaws.com/ecr-nginx:933fcb3
        name: eks-nginx

















