apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: frontend-nginx-ingress
  namespace: default
spec:
  ingressClassName: nginx
  rules:
  - host: ch-jeon.store
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: frontend-nginx
            port:
              number: 80
